services:
  meshmate:
    image: ghcr.io/destaben/meshmate:latest
    container_name: meshmate
    environment:
      # Meshtastic device connection
      - MESHTASTIC_IP=${MESHTASTIC_IP}
      - MESHTASTIC_HOSTNAME=${MESHTASTIC_HOSTNAME}
      
      # Channels to monitor (space-separated list or 'all')
      - CHANNELS=${CHANNELS:-iberia}
      
      # AEMET API key for weather alerts (optional)
      - AEMET_API_KEY=${AEMET_API_KEY}
      
      # Logging configuration
      - LOG_ALL_MESSAGES=${LOG_ALL_MESSAGES:-false}
      
      # API server configuration
      - API_PORT=${API_PORT:-8080}
      - API_HOST=${API_HOST:-0.0.0.0}
    
    # Health check to ensure the container is working properly
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9900/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    
    # Restart policy - always restart on failure, with backoff
    restart: on-failure:10
    
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'
    
    # Network configuration
    network_mode: "host"  # Use host network for Meshtastic TCP access
    volumes:
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw  # Persistent storage for schedules